### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by speqtr** [speqtr/pyqtbind11#2]
**TODO:**

- [x] Update `README.md`;
- [x] Setup python virtualenv using pipenv;
- [x] Setup very basic cmake project;
- [x] Add `.gitignore` file.

**NOTE:** This is just a very basic project structure setup. Nothing fancy.

**Comment by speqtr** [comment]
Related changes were recently pushed to nightly branch. Issue can be closed.

**Comment by speqtr** [comment]
Done.
