### ISSUE TITLE
Implement QML plugin for python modules

### ISSUE THREAD

**Issue by speqtr** [speqtr/pyqtbind11#3]
**TODO:**

- [ ] Add cmake script for python setup;
- [ ] Add cmake script for pybind11 setup;
- [ ] Add cmake script for Qt5 setup;
- [ ] Implement `pyqmlplugin` library.
